####################################################################################
## MAKEFILE
####################################################################################

PROJECT_NAME := uart_puf_cmod-s7-25

M_DEPS += ../common/uart_puf_bd.tcl
M_DEPS += ../../common/cmod-s7-25/cmod-s7-25_system_constr.xdc
M_DEPS += ../../common/cmod-s7-25/cmod-s7-25_system_bd.tcl

LIB_DEPS += util_uart_puf_core

include ../../scripts/project-xilinx.mk
