####################################################################################
## MAKEFILE
####################################################################################

PROJECT_NAME := uart_puf_nexys-a7-100t

M_DEPS += ../common/uart_puf_bd.tcl
M_DEPS += ../../common/nexys-a7-100t/nexys-a7-100t_system_constr.xdc
M_DEPS += ../../common/nexys-a7-100t/nexys-a7-100t_system_bd.tcl

LIB_DEPS += util_uart_puf_core

include ../../scripts/project-xilinx.mk
