####################################################################################
## MAKEFILE
####################################################################################

PROJECT_NAME := uart_puf_arty-a7-35

M_DEPS += ../common/uart_puf_bd.tcl
M_DEPS += ../../common/arty-a7-35/arty-a7-35_system_constr.xdc
M_DEPS += ../../common/arty-a7-35/arty-a7-35_system_bd.tcl

LIB_DEPS += util_uart_puf_core

include ../../scripts/project-xilinx.mk
